from typing import List, Dict, Any

from fastapi import FastAPI, Depends, HTTPException, status

from .auth.auth import basic_auth_dep
from .models.stock_model import StockTicker
from .services.stock_service import stock_service
from .sockets.stock_socket import router as ws_router

app = FastAPI(
    title="Stock Ticker API",
    version="0.1.0",
    summary="Demo FastAPI app with Basic auth, WebSockets, and Pydantic v2 models.",
)

# WebSocket routes (ws://.../ws/ticker)
app.include_router(ws_router, tags=["websocket"])


# --- Lifecycle --------------------------------------------------------------


@app.on_event("startup")
async def on_startup() -> None:
    # Start background async price update loop
    stock_service.start()


@app.on_event("shutdown")
async def on_shutdown() -> None:
    await stock_service.stop()


# --- HTTP Endpoints (all require Basic auth) --------------------------------


@app.get("/health", tags=["system"])
async def health(_: str = Depends(basic_auth_dep)) -> Dict[str, str]:
    """
    Simple health check to verify the service is up.
    Requires HTTP Basic authentication.
    """
    return {"status": "ok"}


@app.get("/me", tags=["auth"])
async def who_am_i(username: str = Depends(basic_auth_dep)) -> Dict[str, str]:
    """
    Return the currently authenticated username.
    Useful for testing Basic auth in Swagger.
    """
    return {"username": username}


@app.get(
    "/tickers",
    response_model=List[StockTicker],
    tags=["stocks"],
    summary="List all tracked tickers",
)
async def list_tickers(_: str = Depends(basic_auth_dep)) -> List[StockTicker]:
    """
    Return the current snapshot for all tracked stock tickers.

    Uses the Pydantic v2 `StockTicker` model generated by datamodel-code-generator,
    so the schema is visible in the OpenAPI/Swagger docs.
    """
    return stock_service.snapshot()


@app.get(
    "/tickers/{symbol}",
    response_model=StockTicker,
    tags=["stocks"],
    summary="Get a single ticker by symbol",
)
async def get_ticker(
    symbol: str,
    _: str = Depends(basic_auth_dep),
) -> StockTicker:
    """
    Return the current state of a single ticker.
    """
    ticker = stock_service.get_ticker(symbol)
    if ticker is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticker '{symbol}' not found",
        )
    return ticker


@app.post(
    "/tickers/{symbol}/reset",
    response_model=StockTicker,
    tags=["stocks"],
    summary="Reset ticker price",
)
async def reset_ticker(
    symbol: str,
    _: str = Depends(basic_auth_dep),
) -> StockTicker:
    """
    Reset a ticker back to its initial price.

    This is a simple demo mutation endpoint to show authenticated POSTs and
    how the service interacts with the in-memory store.
    """
    try:
        return stock_service.reset_ticker(symbol)
    except KeyError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticker '{symbol}' not found",
        )
