# This file is generated by datamodel-code-generator from models/schemas/stock_schema.json.
# You can re-generate it by running: python -m scripts.generate_models

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

class StockTicker(BaseModel):
    """Pydantic v2 model for a stock ticker quote."""

    model_config = ConfigDict(extra="forbid")

    symbol: str = Field(..., description="Ticker symbol, e.g., AAPL")
    price: float
    change: float
    percent_change: float
    last_updated: datetime
