# generated by datamodel-codegen:
#   filename:  /home/shardul/EC/Pydantic-Websockets/src/stock_ticker_api/models/schemas/stock_schema.json
#   timestamp: 2025-11-18T13:08:13+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class StockTicker(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: str
    price: float
    change: float
    percent_change: float
    last_updated: AwareDatetime
